/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibCgmgrJ */

#ifndef _Included_LibCgmgrJ
#define _Included_LibCgmgrJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibCgmgrJ
 * Method:    getReturnCode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_LibCgmgrJ_getReturnCode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    getReturnOutput
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_getReturnOutput
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    ls
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_ls
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    which
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_which
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgList
  (JNIEnv *, jobject);

/*
 * Class:     LibCgmgrJ
 * Method:    cgCreateHierarchy
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgCreateHierarchy
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgCreateGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgCreateGroup
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgDelGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgDelGroup
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgSetValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgSetValue
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgSetCopy
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgSetCopy
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgClassify
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgClassify
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     LibCgmgrJ
 * Method:    cgExec
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LibCgmgrJ_cgExec
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
